In [1]:
import numpy as np


In [9]:
list_of_values = [2,6,2,8,4,0,1,5,7]

# Transformar a lista em um numpy array
array = np.array(list_of_values)

In [10]:
list_of_values

[2, 6, 2, 8, 4, 0, 1, 5, 7]

In [23]:
array

array([2, 6, 2, 8, 4, 0, 1, 5, 7])

In [29]:
print(type(list_of_values))
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


In [83]:
x = [ array[0:3], array[3:6], array[6:9] ]
np.vstack(x)

# np.vstack assume que estamos criando um np.array a partir de sublistas de mesmo tamanho
# ou seja, assume que estamos criando matrizes quadradas

array([[2, 6, 2],
       [8, 4, 0],
       [1, 5, 7]])

In [79]:
matrix = np.array([ array[0:3], array[3:6], array[6:9] ])

In [48]:
matrix

array([[2., 6., 2.],
       [8., 4., 0.],
       [1., 5., 7.]])

In [49]:
matrix.size

9

In [50]:
# Linha 0
matrix[0]

array([2., 6., 2.])

In [52]:
# Média de cada coluna (axis=0)
matrix.mean(axis=0)

array([3.66666667, 5.        , 3.        ])

In [53]:
# Média de cada linha (axis=1)
matrix.mean(axis=1)

array([3.33333333, 4.        , 4.33333333])

In [66]:
a2 = list(matrix.mean(axis=1))

In [67]:
a1 = list(matrix.mean(axis=0))

In [69]:
# Média da matriz completa
a3 = matrix.mean()

In [70]:
# Criando dicionário solution
solution = {'mean: ' : [a1, a2, a3]}

In [71]:
solution

{'mean: ': [[3.6666666666666665, 5.0, 3.0],
  [3.3333333333333335, 4.0, 4.333333333333333],
  3.888888888888889]}

In [75]:
np.var(matrix)

6.987654320987654

In [87]:
list(matrix.std(axis=0))

[3.091206165165235, 0.816496580927726, 2.943920288775949]

In [88]:
matrix.std(axis=1)

array([1.88561808, 3.26598632, 2.49443826])

In [89]:
matrix.std()

2.6434171674156266